
c3p0:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf8
    user: root
    password: 123456
    driverClass: org.mariadb.jdbc.Driver
    minPoolSize: 2
    maxPoolSize: 10
    maxIdleTime: 1800000
    acquireIncrement: 3
    maxStatements: 1000
    initialPoolSize: 3
    idleConnectionTestPeriod: 60
    acquireRetryAttempts: 30
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    testConnectionOnCheckout: false

server:
    context-path: /dev
    port: 80

spring:
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    data:
        rest:
            base-path: /rest
    thymeleaf:
        cache: false
